ユーザー側のホーム画面
SEKI-YUTA/GEEKCAMP_HACKATHON_20230929 pull request #30
Opened 2023-10-03 11:39 UTC by takeki-99

#29

2023-10-03 11:45 UTC, takeki-99 commented
@illionillion よろしくお願いします.

2023-10-03 13:48 UTC, illionillion requested changes
@takeki-99 

選択されたカテゴリが赤にならず「すべて」が赤になっているのでここも修正お願いします！！
オーナー側も修正お願いします！

後2点レビュー内容がありますが、その他は特に問題なく完璧です！！👍

<img width="978" alt="image" src="https://github.com/SEKI-YUTA/GEEKCAMP_HACKATHON_20230929/assets/60034520/d4c78813-cffd-464c-93b3-9413541cc108">

2023-10-03 13:48 UTC, illionillion commented on frontend-react-app/src/features/restaurant/home/UI/Container/RestaurantHomeCon.tsx
> +        photo_url: 'https://k-net01.com/wp-content/uploads/2019/01/smartphone-83.jpg',
三項演算子でこういう風に修正お願いします！！
```typescript
// 画像がない場合は仮の画像を入れる
photo_url: item.photo_url === '' ? 'https://k-net01.com/wp-content/uploads/2019/01/smartphone-83.jpg' : item.photo_url,
```

2023-10-03 13:48 UTC, illionillion commented on frontend-react-app/src/features/restaurant/home/UI/Presentational/RestaurantHomePre.tsx
> +      <Layout title='MaaS'>
`restaurantId`を使用してサーバーからレストラン情報を取得してこの部分にレストラン名を埋め込めるようにしてみて欲しいです！！
```typescript
<Layout title={`${restaurantName} メニューアプリ`}>
```

2023-10-03 14:07 UTC, illionillion commented on frontend-react-app/src/features/restaurant/home/UI/Presentational/RestaurantHomePre.tsx
> +      <Layout title='MaaS'>
追加で、このユーザー側の画面のみヘッダーのログアウトボタンを非表示にするように、ヘッダーのコンポーネントをいじってみて欲しいです！！🙏 @takeki-99 
Layoutコンポーネントから辿っていけばヘッダーのコンポーネント見つかると思います！！

2023-10-04 08:36 UTC, takeki-99 commented
@illionillion  修正終わりました! 確認お願いします🙏

2023-10-04 13:51 UTC, illionillion commented
> 4点レビューしました！！ 確認お願いします！！ @takeki-99

@takeki-99 コンフリクト修正したので、ローカルでの作業前にプルお願いしましす！！

2023-10-05 01:09 UTC, takeki-99 commented
@illionillion 修正しました

2023-10-05 02:21 UTC, illionillion approved these changes

2023-10-05 02:21 UTC, illionillion commented
> @illionillion 修正しました

ありがとうございます！！
マージします！！

2023-10-05 02:23 UTC, merged