Feature user searchmodal
SEKI-YUTA/GEEKCAMP_HACKATHON_20230929 pull request #44
Opened 2023-10-06 10:30 UTC by takeki-99

#21 ユーザー側　検索モーダル

うまく fetch ができなかった

2023-10-06 10:47 UTC, takeki-99 commented
fetch したデータがうまく変換できないで, 困っています😓

2023-10-06 12:57 UTC, illionillion commented
> fetch したデータがうまく変換できないで, 困っています😓

@takeki-99 後で確認するのでとりあえずLintのエラーだけ修正して欲しいです！！

2023-10-06 16:54 UTC, illionillion requested changes
うまくfetchできないの解決になってるかはわからないですがレビューしました！
明日は時間あるのでまたわからないことあれば聞きにきてください！！
@takeki-99

2023-10-06 16:54 UTC, illionillion commented on frontend-react-app/src/features/restaurant/home/UI/Container/RestaurantHomeCon.tsx
> +   * メニュー追加
メニュー絞り込みに変えた方がいいかも

2023-10-06 16:54 UTC, illionillion commented on frontend-react-app/src/features/restaurant/home/UI/Container/RestaurantHomeCon.tsx
> +      const responce = await fetch(`http://localhost:8080/restaurants/${restaurantId}/menus?${menuPriceUpper}`);
READMEをを参考にしてこのようにリクエストを送ればキーワードで検索がかけれると思います！！

```typescript
const responce = await fetch(`http://localhost:8080/restaurants/${restaurantId}/menus?keyword=${keyWord}`);
```

リンクの後ろの`?`の後に`パラメータ名=値`を入れる
追加でパラメータ増やす場合はその続きに`&パラメータ名=値`でキーワードと下限上限を合わせて検索できそう

https://github.com/SEKI-YUTA/GEEKCAMP_HACKATHON_20230929#%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%92%E6%A4%9C%E7%B4%A2%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95

2023-10-06 16:55 UTC, illionillion commented on frontend-react-app/src/features/restaurant/home/UI/Container/RestaurantHomeCon.tsx
> +      const responce = await fetch(`http://localhost:8080/restaurants/${restaurantId}/menus?${menuPriceUpper}`);
GETでのパラメータの渡し方
https://zenn.dev/masahiro_toba/books/3daf7dc0d5dfd7/viewer/c07433

2023-10-07 03:47 UTC, takeki-99 commented
@illionillion 絞り込みできるようになりました

2023-10-07 09:56 UTC, illionillion commented
> @illionillion 絞り込みできるようになりました

@takeki-99 
絞り込みができていることの確認はできました🙆
あとはボタンを「絞り込み」でなく「検索」に直したり、カテゴリーごとの絞り込みをできるようにするだけですね！
引き続きお願いします！！

2023-10-07 14:04 UTC, takeki-99 commented
@illionillion 完成しました！

2023-10-08 09:30 UTC, illionillion reviewed
@takeki-99 1件レビューしました！

それとですが、検索語の左側の「絞り込み結果」がボタンのままになっているので、条件分岐で`disabled`などでクリックできないようにするか別のコンポーネントに置き換えて欲しいです！！

2023-10-08 09:30 UTC, illionillion commented on frontend-react-app/src/features/restaurant/home/UI/Container/RestaurantHomeCon.tsx
> +  const filterMenuModal: JSX.Element = <FilterMenuModal
ここはロジックの部分なのにコンポーネント呼び出しでUIのこと書いてるので`FilterMenuModal`をPreの方で呼び出すようにして欲しいです！！

2023-10-08 09:32 UTC, illionillion commented
@SEKI-YUTA そろそろマージできそうなんうやけどこんな感じで良さそうかな〜？

2023-10-08 10:30 UTC, illionillion commented
@takeki-99 コンフリクト解消したので作業前にプルお願いします！！🙏

2023-10-08 14:00 UTC, merged